import {db,bucket,config} from '@/lib/db';
import {initial,seed} from '@/lib/seed';
import {uid,now,clean,need,hash,protect,password,docValid,session,rate,distance,adminSession,secureEqual} from '@/lib/security';
import {assignedForm,Question} from '@/lib/questions';
// @ts-ignore The pure helper is shared with the Node finance smoke test.
import {TOKEN_CONTRIBUTION_CENTS,pickWinner,toCents} from '@/lib/finance.mjs';
// @ts-ignore The pure adapter is shared with the Node Mercado Pago smoke test.
import {extractPixOrder,verifyWebhookSignature} from '@/lib/mercadopago.mjs';
const json=(v:unknown,status=200,headers:Record<string,string>={})=>Response.json(v,{status,headers:{'Cache-Control':'no-store',...headers}});
async function campaign(id?:string){return await db().prepare(id?'SELECT * FROM campaigns WHERE id=?':"SELECT * FROM campaigns ORDER BY CASE status WHEN 'ativa' THEN 0 ELSE 1 END,rowid DESC LIMIT 1").bind(...(id?[id]:[])).first<Record<string,any>>()}
async function owner(u:any,id:string){const b=await db().prepare('SELECT * FROM businesses WHERE id=?').bind(id).first<any>();need(b&&(u.role==='ADMIN'||u.role==='SUPER_ADMIN'||b.ownerId===u.id),'Você não pode gerenciar esta parada.');return b}
function admin(u:any){need(u?.role==='ADMIN'||u?.role==='SUPER_ADMIN','Acesso exclusivo da administração.')}
async function audit(u:any,action:string,target:string){await db().prepare('INSERT INTO admin_logs (id,userId,action,target,createdAt) VALUES (?,?,?,?,?)').bind(uid(),u.id,action,target,now()).run()}
function active(c:any){need(c?.status==='ativa','Esta campanha não está ativa.');need(!c.start||c.start<=now().slice(0,10),'A campanha ainda não começou.');need(!c.end||c.end>=now().slice(0,10),'A campanha terminou.')}
async function ensureWallet(businessId:string){await db().prepare("INSERT OR IGNORE INTO business_wallets (businessId,availableCents,reservedCents,createdAt,updatedAt) VALUES (?,0,0,?,?)").bind(businessId,now(),now()).run()}
async function prizePool(campaignId:string){await db().prepare("INSERT OR IGNORE INTO campaign_prize_pools (campaignId,totalCents,status,createdAt) VALUES (?,0,'open',?)").bind(campaignId,now()).run();return await db().prepare('SELECT * FROM campaign_prize_pools WHERE campaignId=?').bind(campaignId).first<any>()}
function mercadoPagoConfig(){const token=config('MERCADOPAGO_ACCESS_TOKEN');need(token,'A integração PIX do Mercado Pago ainda não está configurada neste Site.');return {token,base:config('MERCADOPAGO_API_URL')||'https://api.mercadopago.com'}}
async function mercadoPagoFetch(path:string,init:RequestInit={}){const {token,base}=mercadoPagoConfig();const response=await fetch(base+path,{...init,headers:{'Authorization':`Bearer ${token}`,'Content-Type':'application/json',...(init.headers||{})}});const body=await response.json().catch(()=>({})) as any;need(response.ok,body?.message||'O Mercado Pago recusou a operação.');return body as any}
async function createPixCharge(amountCents:number,idempotencyKey:string,externalReference:string,payerEmail:string){const amount=(amountCents/100).toFixed(2);const order=await mercadoPagoFetch('/v1/orders',{method:'POST',headers:{'X-Idempotency-Key':idempotencyKey},body:JSON.stringify({type:'online',total_amount:amount,external_reference:externalReference,processing_mode:'automatic',transactions:{payments:[{amount,payment_method:{id:'pix',type:'bank_transfer'},expiration_time:'PT24H'}]},payer:{email:payerEmail||'financeiro@bebidadeestrada.com'}})});const extracted=extractPixOrder(order);need(extracted.providerReference&&extracted.amountCents===amountCents,'O Mercado Pago retornou uma cobrança inválida.');return {...extracted,expiresAt:order?.transactions?.payments?.[0]?.payment_method?.expiration_time||null}}
async function getMercadoPagoOrder(orderId:string){return extractPixOrder(await mercadoPagoFetch(`/v1/orders/${encodeURIComponent(orderId)}`))}
export async function GET(req:Request){try{await initial();const path=new URL(req.url).pathname;const adminAuthenticated=path==='/api/admin-data'&&await adminSession(req);const u=adminAuthenticated?{id:'password-admin',name:'Administração',email:'',role:'ADMIN',cpfLast:null,phone:null}:await session(req);if(path.startsWith('/api/image/')){const key=path.slice(11);const o=await bucket().get(key);if(!o)return new Response('Imagem não encontrada',{status:404});return new Response(o.body,{headers:{'Content-Type':o.httpMetadata?.contentType||'image/jpeg','Cache-Control':'public,max-age=86400','X-Content-Type-Options':'nosniff'}})}
const c=await campaign(new URL(req.url).searchParams.get('campaign')||undefined);need(c,'Campanha não encontrada.');c.dishWeight=60;
const b=(await db().prepare(`SELECT b.*,d.id dishId,d.name dishName,d.description dishDescription,d.photo dishPhoto,d.category,d.ingredients,d.normalPrice,d.coffee,d.size,d.notes,AVG(CASE WHEN r.status='valid' THEN r.dish END) dishRating,AVG(CASE WHEN r.status='valid' THEN r.coffee END) coffeeRating,SUM(CASE WHEN r.status='valid' THEN 1 ELSE 0 END) reviewCount FROM businesses b JOIN dishes d ON d.businessId=b.id AND d.campaignId=? LEFT JOIN reviews r ON r.businessId=b.id AND r.campaignId=d.campaignId WHERE b.status='approved' GROUP BY b.id`).bind(c.id).all()).results as any[];
for(const x of b){x.score=x.reviewCount?Number(x.dishRating)*0.6+Number(x.coffeeRating)*0.4:null;delete x.ownerId;delete x.cnpj;delete x.email;delete x.phone;delete x.responsible;delete x.legalName}
const ties=String(c.ties).split(',');b.sort((a,b)=>{let d=(b.score??-1)-(a.score??-1);for(const t of ties){if(d)break;const k=({coffee:'coffeeRating',count:'reviewCount',dish:'dishRating'} as any)[t];if(k)d=(b[k]||0)-(a[k]||0)}return d||a.name.localeCompare(b.name)});b.forEach((x,i)=>{x.rank=x.reviewCount?i+1:null;if(!c.publicRanking&&!['ADMIN','SUPER_ADMIN'].includes(u?.role)){x.rank=null;x.score=null;x.dishRating=null;x.coffeeRating=null}});
const me=u?{id:u.id,name:u.name,email:u.email,role:u.role,cpfLast:u.cpfLast,phone:u.phone}:null;
const out:any={adminAuthenticated,campaign:c,businesses:b,user:me,tileUrl:config('MAP_TILE_URL')||'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',tileAttribution:config('MAP_ATTRIBUTION')||'© OpenStreetMap contributors'};
if(u&&['BUSINESS','ADMIN','SUPER_ADMIN'].includes(u.role)){
 const ownedIds=['ADMIN','SUPER_ADMIN'].includes(u.role)?(await db().prepare('SELECT id FROM businesses').all()).results.map((x:any)=>x.id):(await db().prepare('SELECT id FROM businesses WHERE ownerId=?').bind(u.id).all()).results.map((x:any)=>x.id);
 if(ownedIds.length){const marks=ownedIds.map(()=>'?').join(',');const wallet=await db().prepare(`SELECT COALESCE(SUM(availableCents),0) availableCents,COALESCE(SUM(reservedCents),0) reservedCents FROM business_wallets WHERE businessId IN (${marks})`).bind(...ownedIds).first<any>();const deposits=await db().prepare(`SELECT d.*,b.name businessName FROM pix_deposits d JOIN businesses b ON b.id=d.businessId WHERE d.businessId IN (${marks}) ORDER BY d.createdAt DESC LIMIT 20`).bind(...ownedIds).all();const transactions=await db().prepare(`SELECT t.*,b.name businessName FROM wallet_transactions t JOIN businesses b ON b.id=t.businessId WHERE t.businessId IN (${marks}) ORDER BY t.createdAt DESC LIMIT 50`).bind(...ownedIds).all();out.wallet={availableCents:Number(wallet?.availableCents||0),reservedCents:Number(wallet?.reservedCents||0),deposits:deposits.results,transactions:transactions.results}}
 const pool=await prizePool(c.id);out.prizePool={...pool,totalCents:Number(pool?.totalCents||0)};
 if(['ADMIN','SUPER_ADMIN'].includes(u.role)){out.prizeRanking=(await db().prepare("SELECT b.id businessId,b.name,AVG((r.dish*0.6)+(r.coffee*0.4)) average,COUNT(r.id) reviewCount FROM businesses b LEFT JOIN reviews r ON r.businessId=b.id AND r.campaignId=? AND r.status='valid' WHERE b.status='approved' GROUP BY b.id ORDER BY average DESC,reviewCount DESC,b.name").bind(c.id).all()).results}
}
if(u){out.favorites=(await db().prepare('SELECT businessId FROM favorites WHERE userId=?').bind(u.id).all()).results.map((x:any)=>x.businessId);out.myReviews=(await db().prepare('SELECT r.*,b.name businessName FROM reviews r JOIN businesses b ON b.id=r.businessId WHERE r.userId=? ORDER BY r.createdAt DESC').bind(u.id).all()).results;out.owned=(await db().prepare('SELECT b.*,d.id dishId,d.name dishName,d.description dishDescription,d.photo dishPhoto,d.category,d.ingredients,d.normalPrice,d.coffee,d.size,d.notes FROM businesses b LEFT JOIN dishes d ON d.businessId=b.id AND d.campaignId=? WHERE b.ownerId=?').bind(c.id,u.id).all()).results;
if(['BUSINESS','ADMIN','SUPER_ADMIN'].includes(u.role))out.tokens=(await db().prepare("SELECT t.id,t.code,t.status,t.createdAt,t.usedAt,t.businessId,b.name businessName FROM tokens t JOIN businesses b ON b.id=t.businessId WHERE t.campaignId=? AND (b.ownerId=? OR ?=1) ORDER BY t.createdAt DESC LIMIT 500").bind(c.id,u.id,['ADMIN','SUPER_ADMIN'].includes(u.role)?1:0).all()).results;
if(['ADMIN','SUPER_ADMIN'].includes(u.role)){out.allBusinesses=(await db().prepare('SELECT b.*,d.name dishName,d.description dishDescription,d.photo dishPhoto,d.category,d.ingredients,d.normalPrice,d.coffee,d.size,d.notes FROM businesses b LEFT JOIN dishes d ON d.businessId=b.id AND d.campaignId=? ORDER BY b.createdAt DESC').bind(c.id).all()).results;out.users=(await db().prepare('SELECT id,name,email,role,cpfLast,createdAt FROM users ORDER BY createdAt DESC').all()).results;out.reviews=(await db().prepare('SELECT r.*,b.name businessName,u.name userName FROM reviews r JOIN businesses b ON b.id=r.businessId JOIN users u ON u.id=r.userId ORDER BY r.createdAt DESC LIMIT 500').all()).results;out.logs=(await db().prepare('SELECT * FROM admin_logs ORDER BY createdAt DESC LIMIT 100').all()).results;out.campaigns=(await db().prepare('SELECT * FROM campaigns ORDER BY rowid DESC').all()).results;out.questions=(await db().prepare('SELECT * FROM questions ORDER BY category DESC,id').all()).results}}
return json(out);
}catch(e){console.error(e);return json({error:'Não foi possível carregar os dados. Tente novamente.'},503)}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');need(!origin||origin===new URL(req.url).origin,'Origem inválida.');await initial();const path=new URL(req.url).pathname;const adminPath=path==='/api/admin-action'||path==='/api/admin-upload';const adminAuthenticated=adminPath&&await adminSession(req);const u=adminAuthenticated?{id:'password-admin',name:'Administração',email:'',role:'ADMIN'}:await session(req);
if(path==='/api/mercadopago/webhook'){
 const url=new URL(req.url);const payload=await req.json().catch(()=>({})) as any;const orderId=clean(url.searchParams.get('data.id')||payload?.data?.id,200);const signature=req.headers.get('x-signature')||'';const requestId=req.headers.get('x-request-id')||'';const secret=config('MERCADOPAGO_WEBHOOK_SECRET');if(!secret||!(await verifyWebhookSignature(signature,requestId,orderId,secret)))return json({error:'Webhook Mercado Pago não autorizado.'},401);need(orderId,'Webhook Mercado Pago sem Order.');
 const extracted=await getMercadoPagoOrder(orderId);const deposit=await db().prepare('SELECT * FROM pix_deposits WHERE providerReference=?').bind(orderId).first<any>();need(deposit,'Order Mercado Pago não encontrada no Site.');need(extracted.externalReference===deposit.id,'A Order não pertence a este depósito.');need(extracted.amountCents===deposit.amountCents,'O valor da Order não confere com o depósito.');
 if(extracted.status==='paid'&&deposit.status!=='paid'){
  await ensureWallet(deposit.businessId);const result=await db().batch([db().prepare("UPDATE pix_deposits SET status='paid',paidAt=? WHERE id=? AND status!='paid'").bind(now(),deposit.id),db().prepare("UPDATE business_wallets SET availableCents=availableCents+?,updatedAt=? WHERE businessId=?").bind(deposit.amountCents,now(),deposit.businessId),db().prepare("INSERT OR IGNORE INTO wallet_transactions (id,businessId,type,amountCents,reference,metadata,createdAt) VALUES (?,?,?,?,?,?,?)").bind(uid(),deposit.businessId,'pix_credit',deposit.amountCents,`mercadopago:${orderId}`,JSON.stringify({providerReference:orderId}),now())]);need(result[0].meta.changes===1,'Order Mercado Pago já processada.');
 }else if(extracted.status==='failed'&&deposit.status!=='paid')await db().prepare('UPDATE pix_deposits SET status=? WHERE id=?').bind('failed',deposit.id).run();
 return json({ok:true});
}
if(path==='/api/upload'||path==='/api/admin-upload'){need(u,'Entre na sua conta.');need(['BUSINESS','ADMIN','SUPER_ADMIN'].includes(u!.role),'Apenas estabelecimentos podem enviar fotos.');need(Number(req.headers.get('content-length')||0)<6000000,'A foto deve ter até 5 MB.');const form=await req.formData();const file=form.get('file');need(file instanceof File,'Selecione uma foto.');const f=file as File;need(['image/jpeg','image/png','image/webp'].includes(f.type)&&f.size<=5000000,'Envie JPG, PNG ou WebP até 5 MB.');const bytes=await f.arrayBuffer();const sig=new Uint8Array(bytes);need((f.type==='image/jpeg'&&sig[0]===255&&sig[1]===216)||(f.type==='image/png'&&sig[0]===137&&sig[1]===80)||(f.type==='image/webp'&&new TextDecoder().decode(sig.slice(0,4))==='RIFF'),'Arquivo de imagem inválido.');const key=u!.id+'/'+uid();await bucket().put(key,bytes,{httpMetadata:{contentType:f.type}});return json({url:'/api/image/'+key})}
need(Number(req.headers.get('content-length')||0)<50000,'Requisição muito grande.');const p=await req.json() as Record<string,any>;const action=clean(p.action);await rate(req,action==='login'||action==='register'?'auth':'write',action==='login'?20:100);
if(action==='adminLogin'){
 need(path==='/api/admin-action','Use a página /admin para entrar.');await rate(req,'admin-auth',10);
 need(typeof p.password==='string'&&p.password.length>0&&p.password.length<=128,'Informe a senha de administrador.');
 const expected=config('ADMIN_PASSWORD_HASH'),salt=config('ADMIN_PASSWORD_SALT');need(expected&&salt,'Acesso administrativo temporariamente indisponível.');
 need(secureEqual(await password(p.password,salt),expected),'Senha de administrador incorreta.');
 const token=uid()+uid();await db().prepare('INSERT INTO admin_sessions (id,expires,credentialVersion,createdAt) VALUES (?,?,?,?)').bind(await hash(token),Date.now()+14400000,await hash(expected),now()).run();
 await audit({id:'password-admin'},'admin_login','admin');
 return json({ok:true},200,{'Set-Cookie':`be_admin=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=14400`});
}
if(action==='adminLogout'){
 need(path==='/api/admin-action','Ação administrativa inválida.');const raw=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('be_admin='))?.slice(9);if(raw)await db().prepare('DELETE FROM admin_sessions WHERE id=?').bind(await hash(raw)).run();
 return json({ok:true},200,{'Set-Cookie':'be_admin=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});
}
if(action==='setupAdmin')throw new Error('A configuração por perfil foi desativada. Use /admin.');
if(action==='register'||action==='login'){
const email=clean(p.email,200).toLowerCase();need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Informe um e-mail válido.');need(typeof p.password==='string'&&p.password.length>=8&&p.password.length<=128,'A senha deve ter de 8 a 128 caracteres.');let user:any;
if(action==='register'){need(p.consent===true,'Aceite a política de privacidade para continuar.');need(clean(p.name),'Informe seu nome.');const role=p.role==='BUSINESS'?'BUSINESS':'TRAVELER';const cpf=clean(p.cpf).replace(/\D/g,'');if(role==='TRAVELER')need(docValid(cpf,'cpf'),'CPF inválido.');const id=uid(),salt=uid();try{user=await db().prepare("INSERT INTO users (id,email,password,salt,name,role,cpfHash,cpfLast,phone,consentAt,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(cpfHash) DO UPDATE SET email=excluded.email,password=excluded.password,salt=excluded.salt,name=excluded.name,role=excluded.role,phone=excluded.phone,consentAt=excluded.consentAt WHERE users.role='GUEST' RETURNING id").bind(id,email,await password(p.password,salt),salt,clean(p.name,100),role,role==='TRAVELER'?await protect(cpf):null,role==='TRAVELER'?cpf.slice(-2):null,clean(p.phone,30),now(),now()).first();need(user,'Já existe uma conta com este e-mail ou CPF.')}catch{throw new Error('Já existe uma conta com este e-mail ou CPF.')}}
else {user=await db().prepare('SELECT * FROM users WHERE email=?').bind(email).first<any>();need(user&&user.role!=='GUEST'&&(await password(p.password,user.salt))===user.password,'E-mail ou senha incorretos.')}
const token=uid()+uid();await db().prepare('INSERT INTO sessions (id,userId,expires) VALUES (?,?,?)').bind(await hash(token),user.id,Date.now()+604800000).run();return json({ok:true},200,{'Set-Cookie':`be_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`});}
// A guest proof authorizes only one questionnaire, never an account session.
let reviewer:any=null;let reviewAccess='';
if(action==='resolveToken'||action==='guestValidate'){
 await rate(req,'guest-review',40);
 const t=await db().prepare("SELECT t.*,b.name,b.status businessStatus FROM tokens t JOIN businesses b ON b.id=t.businessId WHERE t.code=?").bind(clean(p.code).toUpperCase()).first<any>();
 need(t&&t.status==='disponível'&&t.businessStatus==='approved','Token inválido, utilizado, cancelado ou expirado.');
 const c=await campaign(t.campaignId);active(c);
 if(action==='resolveToken')return json({business:{id:t.businessId,name:t.name},campaign:{id:c!.id,name:c!.name,geoRequired:c!.geoRequired,radius:c!.radius}});
 const cpf=clean(p.cpf).replace(/\D/g,'');need(docValid(cpf,'cpf'),'CPF inválido.');need(p.consent===true,'Confirme o uso do CPF para registrar sua avaliação.');
 if(c!.geoRequired){const b=await db().prepare('SELECT lat,lng FROM businesses WHERE id=?').bind(t.businessId).first<any>();need(Number.isFinite(p.lat)&&Number.isFinite(p.lng),'Permita sua localização para avaliar nesta parada.');need(distance(p.lat,p.lng,b.lat,b.lng)<=c!.radius,'A avaliação só pode ser realizada no local participante.');}
 const cpfHash=await protect(cpf),id=uid();
 await db().prepare("INSERT INTO users (id,email,password,salt,name,role,cpfHash,cpfLast,phone,consentAt,createdAt) VALUES (?,?,?,?,'Viajante sem conta','GUEST',?,?,'',?,?) ON CONFLICT(cpfHash) DO NOTHING").bind(id,id+'@guest.invalid',uid()+uid(),uid(),cpfHash,cpf.slice(-2),now(),now()).run();
 reviewer=await db().prepare('SELECT id,role FROM users WHERE cpfHash=?').bind(cpfHash).first();
 p.businessId=t.businessId;p.campaignId=t.campaignId;
 reviewAccess=uid()+uid();
 // Proof is saved only after the common token and duplicate checks below.
}else if(action==='review'&&typeof p.reviewAccess==='string'){
 reviewer=await db().prepare("SELECT u.id,u.role FROM review_access a JOIN users u ON u.id=a.userId JOIN tokens t ON t.id=a.tokenId WHERE a.id=? AND a.expires>? AND t.code=? AND t.businessId=? AND t.campaignId=?").bind(await hash(p.reviewAccess),Date.now(),clean(p.code).toUpperCase(),clean(p.businessId),clean(p.campaignId)).first();
 need(reviewer,'A autorização expirou. Informe novamente seu CPF.');
}
need(reviewer||u,'Entre na sua conta para continuar.');const user=reviewer||u!;
if(action==='logout'){const raw=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('be_session='))?.slice(11);if(raw)await db().prepare('DELETE FROM sessions WHERE id=?').bind(await hash(raw)).run();return json({ok:true},200,{'Set-Cookie':'be_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}

const c=await campaign(p.campaignId);need(c,'Campanha não encontrada.');const camp=c!;camp.dishWeight=60;
if(action==='profile'){need(clean(p.name),'Informe o nome.');await db().prepare('UPDATE users SET name=?,phone=? WHERE id=?').bind(clean(p.name,100),clean(p.phone,30),user.id).run();}
else if(action==='favorite'){const b=await db().prepare("SELECT id FROM businesses WHERE id=? AND status='approved'").bind(p.businessId).first();need(b,'Parada indisponível.');if(p.remove)await db().prepare('DELETE FROM favorites WHERE businessId=? AND userId=?').bind(p.businessId,user.id).run();else await db().prepare('INSERT OR IGNORE INTO favorites (id,userId,businessId) VALUES (?,?,?)').bind(uid(),user.id,p.businessId).run();}
else if(action==='business'){
need(['BUSINESS','ADMIN','SUPER_ADMIN'].includes(user.role),'Crie uma conta de estabelecimento.');const existing=p.id?await owner(user,p.id):null;const cnpj=clean(p.cnpj).replace(/\D/g,'');need(docValid(cnpj,'cnpj'),'CNPJ inválido.');for(const k of ['name','legalName','responsible','phone','email','address','cep','city','state'])need(clean(p[k]),'Preencha todos os campos do estabelecimento.');need(Number.isFinite(Number(p.lat))&&Number(p.lat)>=-90&&Number(p.lat)<=90&&Number.isFinite(Number(p.lng))&&Number(p.lng)>=-180&&Number(p.lng)<=180,'Coordenadas inválidas.');need(p.acceptBrand===true,'Aceite servir o café oficial da campanha.');const values=[clean(p.name,120),clean(p.legalName),cnpj,clean(p.responsible),clean(p.phone,30),clean(p.email,200),clean(p.address),clean(p.cep,12),clean(p.city,100),clean(p.state,2).toUpperCase(),clean(p.region,30),Number(p.lat),Number(p.lng),clean(p.road,80),clean(p.photo,600)];
if(existing)await db().prepare('UPDATE businesses SET name=?,legalName=?,cnpj=?,responsible=?,phone=?,email=?,address=?,cep=?,city=?,state=?,region=?,lat=?,lng=?,road=?,photo=? WHERE id=?').bind(...values,p.id).run();else await db().prepare('INSERT INTO businesses (name,legalName,cnpj,responsible,phone,email,address,cep,city,state,region,lat,lng,road,photo,id,ownerId,status,demo,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?)').bind(...values,uid(),user.id==='password-admin'?null:user.id,'pending',now()).run();if(user.role!=='BUSINESS')await audit(user,'business',p.id||'new');}
else if(action==='dish'){
await owner(user,p.businessId);need(!camp.locked||['ADMIN','SUPER_ADMIN'].includes(user.role),'Edição de combos bloqueada nesta campanha.');need(clean(p.name)&&Number(p.normalPrice)>camp.price,'Informe um nome e preço normal maior que o preço da campanha.');need(!p.photo||clean(p.photo).startsWith('/api/image/')||['/coffee.jpg','/snack.jpg'].includes(p.photo),'Envie uma imagem pelo botão de upload.');await db().prepare('INSERT INTO dishes (id,businessId,campaignId,name,description,photo,category,ingredients,normalPrice,coffee,size,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(businessId,campaignId) DO UPDATE SET name=excluded.name,description=excluded.description,photo=excluded.photo,category=excluded.category,ingredients=excluded.ingredients,normalPrice=excluded.normalPrice,coffee=excluded.coffee,size=excluded.size,notes=excluded.notes').bind(uid(),p.businessId,camp.id,clean(p.name,120),clean(p.description,1500),clean(p.photo,600),clean(p.category,100),clean(p.ingredients,1000),Number(p.normalPrice),camp.brand,clean(p.size,50),clean(p.notes,1000)).run();if(user.role!=='BUSINESS')await audit(user,'dish',p.businessId);}
else if(action==='createPixDeposit'){
 const b=await owner(user,p.businessId);need(['BUSINESS','ADMIN','SUPER_ADMIN'].includes(user.role),'Apenas estabelecimentos podem adicionar saldo.');const amountCents=toCents(p.amount);need(amountCents>=100,'O aporte mínimo é de R$ 1,00.');const idempotencyKey=clean(p.idempotencyKey,120)||uid();await ensureWallet(b.id);const existing=await db().prepare('SELECT * FROM pix_deposits WHERE idempotencyKey=?').bind(idempotencyKey).first<any>();if(existing)return json({ok:true,deposit:existing});const id=uid();await db().prepare("INSERT INTO pix_deposits (id,businessId,amountCents,providerReference,idempotencyKey,qrCode,copyPaste,status,expiresAt,createdAt) VALUES (?,?,?,NULL,?,NULL,NULL,'pending',NULL,?)").bind(id,b.id,amountCents,idempotencyKey,now()).run();const charge=await createPixCharge(amountCents,idempotencyKey,id,b.email);await db().prepare("UPDATE pix_deposits SET providerReference=?,qrCode=?,copyPaste=?,expiresAt=? WHERE id=?").bind(charge.providerReference,charge.qrCode,charge.copyPaste,charge.expiresAt,id).run();return json({ok:true,deposit:{id,...charge,status:'pending'}});
}
else if(action==='generateTokens'){
 const b=await owner(user,p.businessId);active(camp);need(b.status==='approved','A parada precisa estar aprovada.');need(await db().prepare('SELECT id FROM dishes WHERE businessId=? AND campaignId=?').bind(b.id,camp.id).first(),'Cadastre o combo primeiro.');
 const count=Number(p.count)||1;need(Number.isInteger(count)&&count>0&&count<=100,'Escolha de 1 a 100 tokens.');const totalCents=count*TOKEN_CONTRIBUTION_CENTS;await ensureWallet(b.id);const pool=await prizePool(camp.id);need(pool?.status==='open','O fundo desta campanha já foi encerrado.');const wallet=await db().prepare('SELECT * FROM business_wallets WHERE businessId=?').bind(b.id).first<any>();need(Number(wallet?.availableCents||0)>=totalCents,`Saldo insuficiente. Você precisa de R$ ${(totalCents/100).toFixed(2).replace('.',',')} para gerar ${count} token${count===1?'':'s'}.`);
 const codes=Array.from({length:count},()=> 'BE-'+uid().replace(/-/g,'').slice(0,12).toUpperCase());const statements=[db().prepare('UPDATE business_wallets SET availableCents=availableCents-?,updatedAt=? WHERE businessId=? AND availableCents>=?').bind(totalCents,now(),b.id,totalCents),db().prepare("UPDATE campaigns SET fund=fund+?,contribution=? WHERE id=?").bind(totalCents/100,TOKEN_CONTRIBUTION_CENTS/100,camp.id),db().prepare("UPDATE campaign_prize_pools SET totalCents=totalCents+? WHERE campaignId=? AND status='open'").bind(totalCents,camp.id),db().prepare("INSERT INTO wallet_transactions (id,businessId,type,amountCents,reference,metadata,createdAt) VALUES (?,?,?,?,?,?,?)").bind(uid(),b.id,'token_debit',-totalCents,`tokens:${camp.id}:${codes[0]}`,JSON.stringify({count,campaignId:camp.id}),now()),...codes.map(code=>db().prepare("INSERT INTO tokens (id,businessId,campaignId,code,status,createdAt) VALUES (?,?,?,?,'disponível',?)").bind(uid(),b.id,camp.id,code,now()))];const result=await db().batch(statements);need(result[0].meta.changes===1,'Saldo insuficiente para gerar os tokens.');
 await db().batch(codes.map(code=>db().prepare('INSERT INTO prize_pool_contributions (id,campaignId,tokenId,businessId,amountCents,createdAt) SELECT ?,?,id,?,?,? FROM tokens WHERE code=?').bind(uid(),camp.id,b.id,TOKEN_CONTRIBUTION_CENTS,now(),code)));if(user.role!=='BUSINESS')await audit(user,'tokens',b.id);return json({ok:true,codes});}
else if(action==='cancelToken'){const t=await db().prepare('SELECT * FROM tokens WHERE id=?').bind(p.id).first<any>();need(t,'Token inexistente.');await owner(user,t.businessId);await db().prepare("UPDATE tokens SET status='cancelado' WHERE id=? AND status='disponível'").bind(p.id).run();if(user.role!=='BUSINESS')await audit(user,'cancel_token',p.id);}
else if(action==='validateToken'||action==='guestValidate'||action==='review'){
need(['TRAVELER','GUEST'].includes(user.role),'Somente viajantes podem avaliar.');active(camp);const b=await db().prepare("SELECT * FROM businesses WHERE id=? AND status='approved'").bind(p.businessId).first<any>();need(b,'Parada indisponível.');const t=await db().prepare("SELECT * FROM tokens WHERE code=? AND businessId=? AND campaignId=? AND status='disponível'").bind(clean(p.code).toUpperCase(),p.businessId,camp.id).first<any>();need(t,'Token inválido, utilizado, cancelado ou de outra parada.');need(!(await db().prepare('SELECT id FROM reviews WHERE userId=? AND businessId=? AND campaignId=?').bind(user.id,b.id,camp.id).first()),'Você já avaliou esta parada nesta campanha.');if(camp.geoRequired){need(Number.isFinite(p.lat)&&Number.isFinite(p.lng),'Permita sua localização para avaliar nesta parada.');need(distance(p.lat,p.lng,b.lat,b.lng)<=camp.radius,'A avaliação só pode ser realizada no local participante.')}
if(action==='validateToken'||action==='guestValidate'){const form=await assignedForm(user.id,b.id,camp.id);if(reviewAccess)await db().prepare('INSERT INTO review_access (id,userId,tokenId,expires) VALUES (?,?,?,?)').bind(await hash(reviewAccess),user.id,t.id,Date.now()+3600000).run();return json({ok:true,formId:form.id,questions:form.questions,...(reviewAccess?{reviewAccess}:{}),businessId:b.id,campaignId:camp.id});}
const formRow=await db().prepare('SELECT * FROM review_forms WHERE id=? AND userId=? AND businessId=? AND campaignId=?').bind(clean(p.formId),user.id,b.id,camp.id).first<any>();
need(formRow,'Valide seu token para receber as cinco perguntas.');
const questions:Question[]=JSON.parse(formRow.questions);const answers=p.answers;
need(Array.isArray(answers)&&answers.length===5&&new Set(answers.map((a:any)=>a.questionId)).size===5,'Responda as cinco perguntas sorteadas.');
need(questions.length===5&&questions.filter(q=>q.category==='dish').length===3&&questions.filter(q=>q.category==='coffee').length===2,'Questionário inválido.');
const items=questions.map(q=>{const a=answers.find((x:any)=>x.questionId===q.id);need(a&&Number.isInteger(a.rating)&&a.rating>=1&&a.rating<=5,'Dê uma nota de 1 a 5 para cada pergunta sorteada.');return {...q,rating:a.rating};});
const dish=items.filter(x=>x.category==='dish').reduce((sum,x)=>sum+x.rating,0)/3,coffee=items.filter(x=>x.category==='coffee').reduce((sum,x)=>sum+x.rating,0)/2;
const id=uid();const r=await db().batch([db().prepare("INSERT INTO reviews (id,userId,businessId,campaignId,tokenId,dish,coffee,items,createdAt,lat,lng,ipHash,status) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,'valid' WHERE EXISTS (SELECT 1 FROM tokens WHERE id=? AND status='disponível')").bind(id,user.id,b.id,camp.id,t.id,dish,coffee,JSON.stringify(items),now(),Number.isFinite(p.lat)?p.lat:null,Number.isFinite(p.lng)?p.lng:null,await protect(req.headers.get('cf-connecting-ip')||'unknown'),t.id),db().prepare("UPDATE tokens SET status='utilizado',usedAt=?,userId=? WHERE id=? AND status='disponível' AND EXISTS (SELECT 1 FROM reviews WHERE id=?)").bind(now(),user.id,t.id,id)]);need(r[0].meta.changes===1,'Este token acabou de ser utilizado.');}
else {admin(user);
if(action==='editQuestion'){need(typeof p.text==='string'&&p.text.trim().length>=10&&p.text.trim().length<=350,'Escreva uma pergunta entre 10 e 350 caracteres.');const result=await db().prepare('UPDATE questions SET text=?,updatedAt=? WHERE id=?').bind(p.text.trim(),now(),clean(p.id)).run();need(result.meta.changes===1,'Pergunta não encontrada.');}
else if(action==='businessStatus'){need(['approved','rejected','blocked'].includes(p.status),'Status inválido.');await db().prepare('UPDATE businesses SET status=? WHERE id=?').bind(p.status,p.id).run();}
else if(action==='deleteBusiness')await db().prepare('DELETE FROM businesses WHERE id=?').bind(p.id).run();
else if(action==='deleteDish')await db().prepare('DELETE FROM dishes WHERE businessId=? AND campaignId=?').bind(p.id,camp.id).run();
else if(action==='invalidateReview')await db().prepare("UPDATE reviews SET status='invalid' WHERE id=?").bind(p.id).run();
else if(action==='seed')await seed();
else if(action==='removeDemo')await db().prepare('DELETE FROM businesses WHERE demo=1').run();
else if(action==='closeCampaign'){
 admin(user);const target=await campaign(clean(p.campaignId));need(target,'Campanha não encontrada.');const pool=await prizePool(target.id);need(pool?.status==='open','Esta campanha já foi encerrada.');const rows=(await db().prepare("SELECT b.id businessId,b.name,AVG((r.dish*0.6)+(r.coffee*0.4)) average,COUNT(r.id) reviewCount FROM businesses b LEFT JOIN reviews r ON r.businessId=b.id AND r.campaignId=? AND r.status='valid' WHERE b.status='approved' GROUP BY b.id").bind(target.id).all()).results as any[];const candidates=rows.filter(x=>Number(x.reviewCount)>=100);for(const candidate of candidates){const reached=(await db().prepare("SELECT createdAt FROM reviews WHERE businessId=? AND campaignId=? AND status='valid' ORDER BY createdAt LIMIT 1 OFFSET 99").bind(candidate.businessId,target.id).first<any>());candidate.reachedMinimumAt=reached?.createdAt||''}const winnerId=pickWinner(candidates);const winner=candidates.find(x=>x.businessId===winnerId);const stamp=now();const result=await db().batch([db().prepare("UPDATE campaign_prize_pools SET status='closed',winnerBusinessId=?,winnerAverage=?,winnerReviewCount=?,closedAt=? WHERE campaignId=? AND status='open'").bind(winnerId,winner?.average??null,winner?.reviewCount??null,stamp,target.id),db().prepare("UPDATE campaigns SET status='encerrada' WHERE id=?").bind(target.id),db().prepare("UPDATE tokens SET status='expirado' WHERE campaignId=? AND status='disponível'").bind(target.id)]);need(result[0].meta.changes===1,'Esta campanha já foi encerrada.');await audit(user,'close_campaign',target.id);return json({ok:true,winner:winner||null,totalCents:Number(pool.totalCents||0)});
}
else if(action==='campaign'){
need(clean(p.name)&&clean(p.brand),'Preencha nome e marca.');need(['rascunho','inscrições','ativa','encerrada'].includes(p.status),'Status inválido.');for(const k of ['price','fund','contribution'])need(Number.isFinite(Number(p[k]))&&Number(p[k])>=0,'Valores financeiros inválidos.');need(Number(p.prizePercent)>=0&&Number(p.prizePercent)<=100,'Percentuais devem estar entre 0 e 100.');need(Number(p.radius)>=100&&Number(p.radius)<=10000,'Raio deve ser de 100 a 10.000 metros.');need(!p.start||!p.end||p.start<=p.end,'A data final deve ser posterior à inicial.');need(/^(coffee|count|dish)(,(coffee|count|dish)){2}$/.test(p.ties)&&new Set(p.ties.split(',')).size===3,'Escolha três critérios distintos.');const id=p.new?uid():camp.id;await db().prepare('INSERT INTO campaigns (id,name,status,start,end,price,brand,brandLogo,description,dishWeight,geoRequired,radius,publicRanking,locked,fund,prizePercent,contribution,ties) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,status=excluded.status,start=excluded.start,end=excluded.end,price=excluded.price,brand=excluded.brand,brandLogo=excluded.brandLogo,description=excluded.description,dishWeight=excluded.dishWeight,geoRequired=excluded.geoRequired,radius=excluded.radius,publicRanking=excluded.publicRanking,locked=excluded.locked,fund=excluded.fund,prizePercent=excluded.prizePercent,contribution=excluded.contribution,ties=excluded.ties').bind(id,clean(p.name),p.status,clean(p.start),clean(p.end),Number(p.price),clean(p.brand),clean(p.brandLogo),clean(p.description,1500),60,p.geoRequired?1:0,Number(p.radius),p.publicRanking?1:0,p.locked?1:0,Number(p.fund),Number(p.prizePercent),TOKEN_CONTRIBUTION_CENTS/100,p.ties).run();if(p.status==='encerrada')await db().prepare("UPDATE tokens SET status='expirado' WHERE campaignId=? AND status='disponível'").bind(id).run();}
else throw new Error('Ação desconhecida.');await audit(user,action,p.id||camp.id);}
return json({ok:true});
}catch(e){console.error(e);const msg=e instanceof Error?e.message:'Não foi possível salvar.';return json({error:msg.includes('UNIQUE')?'Este cadastro ou voto já existe.':msg.includes('D1_')?'Não foi possível salvar. Tente novamente.':msg},400)}}
