import {createRequire} from 'node:module';
import {realpathSync,readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {pbkdf2Sync} from 'node:crypto';
import assert from 'node:assert/strict';
const require=createRequire(realpathSync('node_modules/wrangler/package.json'));
const {Miniflare,Log,LogLevel}=require('miniflare');
const testAdminPassword='test-admin-password',salt='test-only-salt';
const mf=new Miniflare({modules:['index.js',...readdirSync('dist/server',{recursive:true}).filter(x=>x.endsWith('.js')&&x!=='index.js')].map(path=>({type:'ESModule',path:resolve('dist/server',path)})),modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{DATA_PEPPER:'test-only',ADMIN_PASSWORD_HASH:pbkdf2Sync(testAdminPassword,salt,100000,32,'sha256').toString('hex'),ADMIN_PASSWORD_SALT:salt},log:new Log(LogLevel.ERROR)});
try{
 const db=await mf.getD1Database('DB');
 for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').filter(x=>x.trim()))await db.prepare(sql).run();
 async function req(cookie,action,p={},expected=200){const endpoint=action.startsWith('admin')||cookie?.startsWith('be_admin=')?'/api/admin-action':'/api/action';const r=await mf.dispatchFetch('https://example.com'+endpoint,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://example.com',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify({action,...p})});const d=await r.json();assert.equal(r.status,expected,action+': '+JSON.stringify(d));return {data:d,cookie:r.headers.get('set-cookie')?.split(';')[0]}}
 async function data(cookie,forcePublic=false){const path=cookie?.startsWith('be_admin=')&&!forcePublic?'/api/admin-data':'/api/data';const r=await mf.dispatchFetch('https://example.com'+path,{headers:cookie?{Cookie:cookie}:{}});assert.equal(r.status,200);return r.json()}
 const start=await data();assert.equal(start.businesses.length,9);assert.equal(start.campaign.dishWeight,60);assert.equal(start.adminAuthenticated,false);assert.equal(start.questions,undefined);
 await req(null,'adminLogin',{password:'incorrect'},400);
 const a=(await req(null,'adminLogin',{password:testAdminPassword})).cookie;
 const ad=await data(a);assert.equal(ad.adminAuthenticated,true);assert.equal(ad.questions.length,45);assert.equal(ad.questions.filter(q=>q.category==='dish').length,27);assert.equal(ad.questions.filter(q=>q.category==='coffee').length,18);
 const publicAdmin=await data(a,true);assert.equal(publicAdmin.adminAuthenticated,false);assert.equal(publicAdmin.questions,undefined);
 console.log('PASS: password-only admin login, independent cookie, private data separation and 45-question seed');
 const businessUser={name:'QA Business',email:'business@example.test',password:'testing-strong-password',role:'BUSINESS',consent:true};
 const b=(await req(null,'register',businessUser)).cookie;
 await req(b,'setupAdmin',{key:'any-old-key'},400);await req(b,'editQuestion',{id:'dish-01',text:'Uma tentativa sem permissão de administrador'},400);await req(b,'businessStatus',{id:'demo-motoristas',status:'blocked'},400);
 await db.prepare("UPDATE users SET role='SUPER_ADMIN' WHERE email=?").bind(businessUser.email).run();await req(b,'businessStatus',{id:'demo-motoristas',status:'blocked'},400);await db.prepare("UPDATE users SET role='BUSINESS' WHERE email=?").bind(businessUser.email).run();
 await req(b,'business',{name:'QA Parada',legalName:'QA LTDA',cnpj:'11222333000181',responsible:'QA Owner',phone:'3500000000',email:'qa@example.test',address:'Rua de teste',cep:'37950000',city:'São Sebastião do Paraíso',state:'MG',region:'Sudeste',lat:-20.91,lng:-46.99,road:'BR-265',acceptBrand:true});
 let d=await data(b);const id=d.owned[0].id;assert.equal(d.owned[0].status,'pending');assert.equal(d.businesses.some(x=>x.id===id),false);
 await req(b,'generateTokens',{businessId:id,count:1},400);
 await req(b,'dish',{businessId:id,name:'Combo QA',description:'Teste',normalPrice:30,size:'150 ml',photo:'/coffee.jpg'});
 await req(a,'businessStatus',{id,status:'approved'});assert((await data()).businesses.some(x=>x.id===id));
 await db.prepare("INSERT INTO business_wallets (businessId,availableCents,reservedCents,createdAt,updatedAt) VALUES (?,1000,0,?,?)").bind(id,new Date().toISOString(),new Date().toISOString()).run();
 console.log('PASS: old setup disabled, legacy user role cannot bypass password, business approval and combo');
 const tokens=(await req(b,'generateTokens',{businessId:id,count:3})).data.codes;
 const traveler={name:'QA Traveler',email:'traveler@example.test',password:'testing-strong-password',role:'TRAVELER',cpf:'52998224725',consent:true};
 const u=(await req(null,'register',traveler)).cookie;
 await req(null,'register',{...traveler,email:'duplicate@example.test'},400);await req(u,'generateTokens',{businessId:id,count:1},400);await req(u,'validateToken',{businessId:'demo-motoristas',code:tokens[0]},400);
 const f=(await req(u,'validateToken',{businessId:id,code:tokens[0]})).data;
 assert.equal(f.questions.length,5);assert.equal(f.questions.filter(q=>q.category==='dish').length,3);assert.equal(f.questions.filter(q=>q.category==='coffee').length,2);
 const again=(await req(u,'validateToken',{businessId:id,code:tokens[1]})).data;assert.equal(again.formId,f.formId);assert.deepEqual(again.questions,f.questions);
 const oldText=f.questions[0].text;await req(a,'editQuestion',{id:f.questions[0].id,text:'Como você avalia esta experiência gastronômica do lanche?'});
 assert.equal((await data(a)).questions.find(q=>q.id===f.questions[0].id).text,'Como você avalia esta experiência gastronômica do lanche?');assert.equal((await req(u,'validateToken',{businessId:id,code:tokens[0]})).data.questions[0].text,oldText);
 console.log('PASS: server assigns 3 snack + 2 coffee, stable assignment and edit-proof historical snapshot');
 const answers=f.questions.map(q=>({questionId:q.id,rating:q.category==='dish'?5:1}));
 await req(u,'review',{businessId:id,code:tokens[0],formId:f.formId,answers:answers.slice(0,4)},400);
 await req(u,'review',{businessId:id,code:tokens[0],formId:f.formId,answers:answers.map((x,i)=>i?x:{questionId:'dish-nonexistent',rating:5})},400);
 await req(u,'review',{businessId:id,code:tokens[0],formId:f.formId,answers:answers.map((x,i)=>i?x:{...x,rating:6})},400);
 await req(u,'review',{businessId:id,code:tokens[0],formId:f.formId,answers});
 let ranking=(await data()).businesses.find(x=>x.id===id);assert.equal(ranking.score,3.4);assert.equal(ranking.reviewCount,1);
 await req(u,'review',{businessId:id,code:tokens[0],formId:f.formId,answers},400);await req(u,'review',{businessId:id,code:tokens[1],formId:f.formId,answers},400);
 const saved=(await data(u)).myReviews[0];assert.equal(JSON.parse(saved.items)[0].text,oldText);
 console.log('PASS: all five answers required, tamper prevention, 1–5 bounds, 60/40 score 3.4 and no duplicate votes');
 const v=(await req(null,'register',{...traveler,email:'second@example.test',cpf:'11144477735'})).cookie;
 await req(v,'review',{businessId:id,code:tokens[1],formId:f.formId,answers},400);
 const f2=(await req(v,'validateToken',{businessId:id,code:tokens[1]})).data;
 const payload={businessId:id,code:tokens[1],formId:f2.formId,answers:f2.questions.map(q=>({questionId:q.id,rating:5}))};
 const race=await Promise.all([1,2].map(()=>mf.dispatchFetch('https://example.com/api/action',{method:'POST',headers:{'Content-Type':'application/json',Cookie:v,Origin:'https://example.com'},body:JSON.stringify({action:'review',...payload})})));
 assert.deepEqual(race.map(r=>r.status).sort(),[200,400]);ranking=(await data()).businesses.find(x=>x.id===id);assert.equal(ranking.reviewCount,2);assert(Math.abs(ranking.score-4.2)<1e-9);
 console.log('PASS: cross-user questionnaire rejected, concurrent token safe, two-review mean equals 4.2');
 const own=await data(b);assert(!JSON.stringify(own.tokens).includes('cpf'));assert(!JSON.stringify(own.tokens).includes('userId'));
 const fd=new FormData();fd.set('file',new File([readFileSync('public/coffee.jpg')],'photo.jpg',{type:'image/jpeg'}));const uploadRequest=new Request('https://example.com/api/upload',{method:'POST',body:fd});const upload=await mf.dispatchFetch('https://example.com/api/upload',{method:'POST',headers:{Cookie:b,Origin:'https://example.com','Content-Type':uploadRequest.headers.get('content-type')},body:await uploadRequest.arrayBuffer()});assert.equal(upload.status,200);const photo=await upload.json();assert.equal((await mf.dispatchFetch('https://example.com'+photo.url)).status,200);
 await req(a,'removeDemo');assert.equal((await data()).businesses.length,1);await req(a,'seed');assert.equal((await data()).businesses.length,10);await db.prepare("INSERT OR IGNORE INTO business_wallets (businessId,availableCents,reservedCents,createdAt,updatedAt) SELECT id,1000,0,?,? FROM businesses WHERE demo=1").bind(new Date().toISOString(),new Date().toISOString()).run();assert.equal((await data(a)).questions.length,45);
 console.log('PASS: CPF privacy, uploads, demo removal and question bank persists');
 // Guest identity is scoped to a token; it never creates an account session.
 const guestCodes=(await req(b,'generateTokens',{businessId:id,count:3})).data.codes;
 const resolved=(await req(null,'resolveToken',{code:guestCodes[0]})).data;
 assert.equal(resolved.business.id,id);assert.equal(resolved.campaign.id,start.campaign.id);
 await req(null,'resolveToken',{code:'BE-INVALID'},400);
 const guestInput={code:guestCodes[0],cpf:'12345678909',consent:true};
 await req(null,'guestValidate',{...guestInput,cpf:'00000000000'},400);
 await req(null,'guestValidate',{...guestInput,consent:false},400);
 const guestResponse=await req(null,'guestValidate',guestInput);assert.equal(guestResponse.cookie,undefined);
 const guest=guestResponse.data;assert.equal(guest.questions.length,5);assert.equal(guest.questions.filter(q=>q.category==='dish').length,3);
 assert.equal((await data()).user,null);assert.equal(guest.email,undefined);assert.equal(guest.userId,undefined);
 const gp={code:guestCodes[0],businessId:id,campaignId:start.campaign.id,formId:guest.formId,reviewAccess:guest.reviewAccess,answers:guest.questions.map(q=>({questionId:q.id,rating:4}))};
 await req(null,'profile',{reviewAccess:guest.reviewAccess,name:'Forbidden'},400);
 await req(null,'review',{...gp,reviewAccess:'forged'},400);
 await req(null,'review',{...gp,code:guestCodes[1]},400);
 await req(null,'review',gp);
 await req(null,'review',gp,400);
 await req(null,'guestValidate',{...guestInput,code:guestCodes[1]},400);
 const registered=(await req(null,'register',{...traveler,email:'guest-now-member@example.test',cpf:guestInput.cpf})).cookie;
 const linked=await data(registered);assert.equal(linked.user.role,'TRAVELER');assert.equal(linked.myReviews.length,1);assert.equal(linked.myReviews[0].dish,4);
 await req(registered,'validateToken',{businessId:id,code:guestCodes[1]},400);
 await req(null,'register',{...traveler,email:'steal@example.test',cpf:guestInput.cpf},400);
 // Existing accounts may review with CPF without exposing account data or password access.
 const otherCode=(await req(a,'generateTokens',{businessId:'demo-motoristas',count:1})).data.codes[0];
 const existing=(await req(null,'guestValidate',{code:otherCode,cpf:traveler.cpf,consent:true})).data;
 await req(null,'review',{code:otherCode,businessId:'demo-motoristas',campaignId:start.campaign.id,reviewAccess:existing.reviewAccess,formId:existing.formId,answers:existing.questions.map(q=>({questionId:q.id,rating:5}))});
 assert.equal((await data(u)).myReviews.length,2);
 // Expired guest capability cannot be reused.
 const exp=(await req(null,'guestValidate',{code:guestCodes[2],cpf:'39053344705',consent:true})).data;
 await db.prepare('UPDATE review_access SET expires=0').run();
 await req(null,'review',{...gp,code:guestCodes[2],reviewAccess:exp.reviewAccess,formId:exp.formId,answers:exp.questions.map(q=>({questionId:q.id,rating:5}))},400);
 console.log('PASS: QR resolves exact campaign, guest CPF/consent, scoped access, duplicates, expiry, later account links history and existing accounts stay private');
 await req(a,'campaign',{...(await data(a)).campaign,dishWeight:99,publicRanking:false,geoRequired:true,radius:500});assert.equal((await data()).campaign.dishWeight,60);assert.equal((await data()).businesses.find(x=>x.id===id).score,null);
 const t3=(await req(a,'generateTokens',{businessId:'demo-motoristas',count:1})).data.codes[0];await req(v,'validateToken',{businessId:'demo-motoristas',code:t3},400);await req(v,'validateToken',{businessId:'demo-motoristas',code:t3,lat:0,lng:0},400);await req(v,'validateToken',{businessId:'demo-motoristas',code:t3,lat:-20.275,lng:-45.006});
 await req(a,'campaign',{...(await data(a)).campaign,status:'encerrada'});await req(v,'validateToken',{businessId:'demo-motoristas',code:t3,lat:-20.275,lng:-45.006},400);
 await req(a,'adminLogout');assert.equal((await data(a)).adminAuthenticated,false);await req(a,'editQuestion',{id:'dish-01',text:'Texto não autorizado após sair do painel.'},400);
 await req(u,'logout');await req(u,'profile',{name:'Forbidden'},400);
 console.log('PASS: fixed weighting, private ranking, geolocation, expiry and session revocation');
 console.log('All end-to-end checks passed. Test database is isolated and discarded.');
}finally{await mf.dispose()}
